version: '3'

services:
  # Java Spring Boot API
  api:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always

  # NextJS React Client
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - api