# spring boot
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/vitalityvibe

# jwt
jwt:
  secret: secret
  expiration: 86400000 # 1 day
  tokenPrefix: Bearer
  headerString: Authorization