# /server/src/main/resources/application.yml 
#
# This file contains the configuration for the Spring Boot application.
#
# The application configuration is divided into two sections:
#  - Spring Boot application configuration
#  - Application configuration
#
# The Spring Boot application configuration is used to configure the Spring Boot application.
# The Application configuration is used to configure the application.
#

### Spring Boot application configuration ###
spring:
  # postgres database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/vitalityvibe
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  # jpa configuration for hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

### Appliction configuration ###
application:
  # jwt configuration
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # long hex string
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days