# spring boot
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:1234qwer@rs0.ft3whlf.mongodb.net/vitalityvibe?retryWrites=true&w=majority

# jwt
jwt:
  secret: secret
  expiration: 86400000 # 1 day
  tokenPrefix: Bearer
  headerString: Authorization