name: lint-pr

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install commitlint
        run: bun add global @commitlint/cli @commitlint/config-conventional

      - name: Configure commitlint
        run: echo "module.exports = {extends${{':'}} ['@commitlint/config-conventional']}" > commitlint.config.js

      - name: Lint PR
        run: echo ${{ github.event.pull_request.title }}
