name: Build

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  client-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: client
        run: bun install

      - name: Lint
        working-directory: client
        run: bun run lint

  server-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: vitalityvibe
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: vitalityvibe
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Test with Maven
        working-directory: server
        run: mvn -B test --file pom.xml