name: Build

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  client-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: client
        run: bun install

      - name: Lint
        working-directory: client
        run: bun run lint
