name: Build

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  client-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Change Dir into project
        run: cd ./client

      - name: list files
        run: ls -la

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint
